version: '2'

services:
  bd:
    container_name: mysql
    image: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
        - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
        - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
        - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
        - db:/var/lib/mysql
  backend:
    container_name: devopsproject
    image: marwen14/devops:latest
    restart: on-failure
    env_file: ./.env
    ports:
        - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
        SPRING_APPLICATION_JSON: '{
            "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
            "spring.datasource.username" : "$MYSQLDB_USER",
            "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
            "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
            "spring.jpa.hibernate.ddl-auto" : "update"
          }'
    depends_on:
      - "bd"
  frontend:
    container_name: devopsangular
    image: devopsprojectclient
    restart: on-failure
    ports:
      - "4200:4200"